project_id = "yfutdebllhsawqzihysx"

[functions.ai-worker]
verify_jwt = false

[functions.test-vertex-ai]
verify_jwt = true

[functions.fix-invalid-prices]
verify_jwt = true

[functions.update-prices]
verify_jwt = false

[functions.check-price-alerts]
verify_jwt = false

[functions.generate-product-images]
verify_jwt = false